name: DPIBypass
options:
  deploymentTarget:
    iOS: "15.0"

settings:
  base:
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_IDENTITY: ""
    CODE_SIGNING_REQUIRED: "NO"
    CODE_SIGNING_ALLOWED: "NO"

targets:
  DPIBypass:
    type: application
    platform: iOS
    sources:
      - DPIBypass/
      - Shared/
    info:
      path: DPIBypass/App/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.voiplet.dpibypass
    entitlements:
      path: DPIBypass/DPIBypass.entitlements
    dependencies:
      - target: PacketTunnelExtension
        embed: true

  PacketTunnelExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: PacketTunnelExtension/
        excludes:
          - "lwip/lwip-src/.vscode/**"
          - "lwip/lwip-src/.github/**"
          - "lwip/lwip-src/CMakeLists.txt"
          - "lwip/lwip-src/COPYING"
          - "lwip/lwip-src/FEATURES"
          - "lwip/lwip-src/FILES"
          - "lwip/lwip-src/codespell_*.sh"
          - "lwip/lwip-src/src/FILES"
          - "lwip/lwip-src/src/Filelists.*"
          - "lwip/lwip-src/src/include/compat/**"
          - "lwip/lwip-src/src/include/netif/**"
          - "lwip/lwip-src/src/include/lwip/apps/**"
          - "lwip/lwip-src/src/core/dns.c"
          - "lwip/lwip-src/src/core/raw.c"
          - "lwip/lwip-src/src/core/stats.c"
          - "lwip/lwip-src/src/core/altcp.c"
          - "lwip/lwip-src/src/core/altcp_alloc.c"
          - "lwip/lwip-src/src/core/altcp_tcp.c"
          - "lwip/lwip-src/src/core/ipv4/acd.c"
          - "lwip/lwip-src/src/core/ipv4/autoip.c"
          - "lwip/lwip-src/src/core/ipv4/dhcp.c"
          - "lwip/lwip-src/src/core/ipv4/etharp.c"
          - "lwip/lwip-src/src/core/ipv4/igmp.c"
          - "lwip/lwip-src/**/*.in"
          - "lwip/lwip-src/**/*.cmake"
          - "lwip/lwip-src/**/*.mk"
          - "lwip/lwip-src/**/*.sh"
      - Shared/
    info:
      path: PacketTunnelExtension/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.voiplet.dpibypass.tunnel
        SWIFT_OBJC_BRIDGING_HEADER: PacketTunnelExtension/PacketTunnelExtension-Bridging-Header.h
        HEADER_SEARCH_PATHS:
          - "$(inherited)"
          - "$(SRCROOT)/PacketTunnelExtension/lwip"
          - "$(SRCROOT)/PacketTunnelExtension/lwip/lwip-src/src/include"
    entitlements:
      path: PacketTunnelExtension/PacketTunnelExtension.entitlements
